# Generated by Django 5.1.1 on 2024-10-26 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("commerce", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("product_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartlineitem",
            name="bounty",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="product_management.bounty"
            ),
        ),
        migrations.AddField(
            model_name="cartlineitem",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="line_items", to="commerce.cart"
            ),
        ),
        migrations.AddField(
            model_name="cartlineitem",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
    ]
