# Generated by Django 5.1.1 on 2024-10-27 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("commerce", "0001_initial"),
        ("product_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartlineitem",
            name="bounty",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="product_management.bounty"
            ),
        ),
        migrations.AddField(
            model_name="cartlineitem",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="line_items", to="commerce.cart"
            ),
        ),
    ]
