# Generated by Django 5.1.1 on 2024-10-27 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("commerce", "0001_initial"),
        ("product_management", "0001_initial"),
        ("talent", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contributorpointaccount",
            name="person",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="point_account", to="talent.person"
            ),
        ),
        migrations.AddField(
            model_name="contributorpointtransaction",
            name="point_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="commerce.contributorpointaccount",
            ),
        ),
        migrations.AddField(
            model_name="contributorwallet",
            name="person",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="wallet", to="talent.person"
            ),
        ),
        migrations.AddField(
            model_name="contributorwallettransaction",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="commerce.contributorwallet",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="carts", to="commerce.organisation"
            ),
        ),
        migrations.AddField(
            model_name="organisationpointaccount",
            name="organisation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="point_account", to="commerce.organisation"
            ),
        ),
        migrations.AddField(
            model_name="organisationpointgrant",
            name="granted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="granted_points",
                to="talent.person",
            ),
        ),
        migrations.AddField(
            model_name="organisationpointgrant",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="point_grants", to="commerce.organisation"
            ),
        ),
        migrations.AddField(
            model_name="cartlineitem",
            name="point_grant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cart_line_items",
                to="commerce.organisationpointgrant",
            ),
        ),
        migrations.AddField(
            model_name="organisationpointgrantrequest",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="point_grant_requests",
                to="commerce.organisation",
            ),
        ),
        migrations.AddField(
            model_name="organisationpointgrantrequest",
            name="requested_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="point_grant_requests",
                to="talent.person",
            ),
        ),
        migrations.AddField(
            model_name="organisationpointgrant",
            name="grant_request",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resulting_grant",
                to="commerce.organisationpointgrantrequest",
            ),
        ),
        migrations.AddField(
            model_name="organisationwallet",
            name="organisation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="wallet", to="commerce.organisation"
            ),
        ),
        migrations.AddField(
            model_name="organisationwallettransaction",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="commerce.organisationwallet",
            ),
        ),
        migrations.AddField(
            model_name="pointorder",
            name="cart",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="point_order", to="commerce.cart"
            ),
        ),
        migrations.AddField(
            model_name="pointtransaction",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_transactions",
                to="commerce.organisationpointaccount",
            ),
        ),
        migrations.AddField(
            model_name="productpointaccount",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_point_account",
                to="product_management.product",
            ),
        ),
        migrations.AddField(
            model_name="pointtransaction",
            name="product_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_transactions",
                to="commerce.productpointaccount",
            ),
        ),
        migrations.AddField(
            model_name="pointorder",
            name="product_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="point_orders",
                to="commerce.productpointaccount",
            ),
        ),
        migrations.AddField(
            model_name="productpointrequest",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="point_requests",
                to="product_management.product",
            ),
        ),
        migrations.AddField(
            model_name="productpointrequest",
            name="requested_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_point_requests",
                to="talent.person",
            ),
        ),
        migrations.AddField(
            model_name="productpointrequest",
            name="resulting_transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_point_request",
                to="commerce.pointtransaction",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="cart",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="sales_order", to="commerce.cart"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="sales_orders", to="commerce.organisation"
            ),
        ),
        migrations.AddField(
            model_name="organisationwallettransaction",
            name="related_order",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="commerce.salesorder"
            ),
        ),
        migrations.AddField(
            model_name="salesorderlineitem",
            name="sales_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="line_items", to="commerce.salesorder"
            ),
        ),
        migrations.AddField(
            model_name="organisationpointgrant",
            name="sales_order_item",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resulting_grant",
                to="commerce.salesorderlineitem",
            ),
        ),
    ]
